apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "labels" . | indent 6 }}
spec:
  selector:
    matchLabels:
{{ include "selectorLabels" . | indent 6 }}
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      {{- if .Values.deployment.annotations }}
      annotations:
{{ tpl .Values.deployment.annotations . | indent 8 }}
      {{- end }}
      labels:
{{ include "labels" . | indent 8 }}
    spec:
    {{- if .Values.deployment.affinity }}
      affinity:
        {{ tpl .Values.deployment.affinity . | nindent 8 | trim }}
    {{- end }}
    {{- if .Values.deployment.tolerations }}
      tolerations:
        {{ tpl .Values.deployment.tolerations . | nindent 8 | trim }}
    {{- end }}
      {{- if .Values.deployment.priorityClassName }}
      priorityClassName: {{ .Values.deployment.priorityClassName | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resources.requests.cpu }}
              memory: {{ .Values.deployment.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.resources.limits.cpu }}
              memory: {{ .Values.deployment.resources.limits.memory }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
      {{ tpl .Values.deployment.nodeSelector . | indent 8 | trim }}
      {{- end }}