name: push-main

# 1. Run unit and integration tests
# 2. Push containers to AWS ECR with tag based on incrementing build number
# 3. Recommit an update to the chart's deployments with the updated build number in the `deployment` branch

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'chart/**'

jobs:

  build:
    name: Build containers
    runs-on: ubuntu-latest
    env:
      NETWORK_NAME: mainnet
      DEPLOYMENT_ENVIRONMENT: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: icon-explorer-frontend
          IMAGE_TAG: dev-${{ github.run_number }}
        run: |
          docker build --target prod --build-arg REACT_APP_NETWORK_NAME=$NETWORK_NAME --build-arg REACT_APP_DEPLOYMENT_ENVIRONMENT=$DEPLOYMENT_ENVIRONMENT -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  update-values:
    name: Update values files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: geometry-labs/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Update prod-berlin-us-west-2 deployment values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/berlin/tracker-frontend/values.yaml'
          propertyPath: 'deployment.image.tag'
          value: dev-${{ github.run_number }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod-lisbon-us-west-2 deployment values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/lisbon/tracker-frontend/values.yaml'
          propertyPath: 'deployment.image.tag'
          value: dev-${{ github.run_number }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update dev-mainnet deployment values file and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/dev/mainnet/tracker-frontend/values.yaml'
          propertyPath: 'deployment.image.tag'
          value: dev-${{ github.run_number }}
          branch: main
          createPR: 'false'
          message: 'tracker-frontend dev deployment (mainnet) image version to ${{ github.run_number }}'
#          token: ${{ secrets.ICON_CHARTS_PAT }}
#          updateFile: true
          updateFile: true
          commitChange: false

      - name: Configure credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.ICON_CHARTS_PAT }}'
          global: true

      - name: Commit all updates
        run: |
          git add -A
          git commit -m "tracker-frontend dev and testnet deployment image versions to ${{ github.run_number }}"
          git push origin
        working-directory: charts

      - name: Push tags
        run: |
          git tag -f tracker-frontend-prod-uswest2
          git push -f origin --tags
        working-directory: charts
